- examples/VaryingCDF.cpp
- src/core/DenseMatrix.cpp
- src/core/DenseMatrix.h
- src/core/SparseMatrix.cpp
- src/core/SparseMatrix.h
- src/function/VaryingCDF.cpp
- src/function/VaryingCDF.h
- test/unit/VaryingCDFTest.cpp
Added VaryingCDF, a general parameter dependant CDF. Also added Print functionality to the matrix classes.
A VaryingCDF is a CDF whose underlying generating kernels parameters
(e.g. the stdev of the Gaussian that makes the matrix) can depend on
general functions of the fit parameters.
Also added print functions to the matrix classes.
Usage:
Gaussian gaus("gaus",0,1);
gaus.RenameParameter("means_0","mean");
gaus.RenameParameter("stddevs_0","std");
VaryingCDF smearer("smearer");
smearer.SetKernal(&gaus)
smearer.SetDependance("std",ploy(see note));
The above creates a VaryingCDF whose gaussian kernel has a variable
stddev which goes like the function ploy.
note:
Where 'ploy' is a function that takes a vector of doubles that
represents the bin in which you are evaluating on e.g. fitting in …
> Added VaryingCDF, a general parameter dependant CDF. Also added Print

- examples/simpleFit.cpp
- examples/simpleSystematicFit.cpp
- examples/systematicFit.cpp
- src/core/SparseMatrix.cpp
- src/core/SparseMatrix.h
- src/fitutil/BinnedEDManager.cpp
- src/fitutil/SystematicManager.cpp
- src/fitutil/SystematicManager.h
- src/teststat/BinnedNLLH.cpp
- src/teststat/BinnedNLLH.h
- src/teststat/ChiSquare.cpp
- test/unit/SystematicManagerTest.cpp
The SystematicManager now stores its systematics in map of vectors.
Each vector is referred to as a group and is keyed by the name of that
group. Systematics are added to a group through the BinnedNLLH (lh)
like:
lh.AddSystematic(Systematic, "groupName");
The order in which the systematic is added to a group is the order in
which it is applied. If a group name is not specified, the systematic is
added the global ("") group which is then *always* applied to all EDs
before any other groups.
A ED is then associated with a vector of groups that will be applied to
that ED in that order:
std::vector<std::string> appliedSys;
appliedSys.push_back("GroupA");
appliedSys.push_back("GroupB");
lh.AddDist(ED,"appliedSys")
Global and group bases systematics may be applied together.
See …
> Systematics can be associated with a group of EDs.

- examples/simpleFit.cpp
- examples/simpleSystematicFit.cpp
- examples/systematicFit.cpp
- src/dist/BinnedED.cpp
- src/dist/BinnedED.h
- src/fitutil/BinnedEDManager.cpp
- src/fitutil/SystematicManager.cpp
- src/fitutil/SystematicManager.h
- src/histogram/Histogram.cpp
- src/histogram/Histogram.h
- src/teststat/BinnedNLLH.cpp
- src/teststat/BinnedNLLH.h
This deals with the review comments I left on PR #3 .
An overview:
- add description of the systematics group logic to SystematicManager.h
- add function AddPadding to Histogram and BinnedED, so that is can be used by the users as well as the examples and to avoid code repetition - it adds very small numbers to 0 content bins
- move AddDist back to AddPdf and add back AddPds in BinnedNLLH to improve backward compatibility and avoid unnecessary additional methods
- clean up simpleSystematicFit example a little 
- fix logic for when there is no systematics (because now there is always "" group, but can be empty)
- added description and changed function names in systematicFit example
No changes in functionality expected compared to PR3 apart from the simple logic change. Examples produce the …
> Address review comments from PR#3 - systematics groups

- src/data/DataSetGenerator.cpp
- src/data/DataSetGenerator.h
Allows for setting the flag for replacing events in the detatset to be set separately for each contribution rather than globally.
> Make bootstrap in DataSetgenerator a vector

- src/core/Combinations.cpp
- src/core/Combinations.hpp
- src/data/IO.cpp
- src/data/IO.h
- src/dist/BinnedED.cpp
- src/dist/BinnedED.h
- src/eventSystematic/EventShift.cpp
- src/histogram/HistTools.h
- src/histogram/HistTools.hpp
- src/histogram/Histogram.cpp
- src/histogram/Histogram.h
There are 3 commits, not really related to each other, but two are really minor:
- add possibility to name a tree when saving a dataset - this can save some pain if you happen to need them saved with different name, defaults to the old "oxsx_saved", so shouldn't change anything if you don't
- fix bug in EventShift - should definitely be + not *
The bigger one is adding functionality to create slices of BinnedEDs and histograms. This is really useful if you have to look at multiD distributions and projections are just not enough. 
- The new Get1DSlices function in DistTools get all the bin combinations in the requested slice observable. 
- BinnedED::GetSlice gets the name of the slice right and calls the next thing for the corresponding histogram
- Histogram::GetSlice actually gets the …
> Add slices of distributions and two other minor tweaks for HMC

- util/calc_eff_rad
- util/make_simple_data
- util/prune_flat_tree
Python code in the util sub-directory has been only compatible with Python 2 historically. This PR makes the minor modifications necessary so that this code should be able to run with both Python 2 & 3. This is important as future users will certainly want to use Python 3; Python 2 is going/has gone end-of-life. Moreover, the solar oscillation analysis code is now using Python 3, and breaks when trying to call `util/prune_flat_tree`.
I have used the Python `2to3` package to get the code usable in Python 3; to keep backwards compatibility for Python 2 I have added the `from __future__ import ... ` lines where appropriate. The only changes `2to3` has made are the syntax for `print()` statements.
I have tested `util/prune_flat_tree` with both the standard Oxford RAT environment of ROOT …
> Make util code Python 2 & 3 compatible

- src/data/DataSetGenerator.cpp
- test/unit/BinnedEDManagerTest.cpp
- test/unit/BinnedEDShrinkerTest.cpp
- test/unit/BinnedEDTest.cpp
- test/unit/BinnedNLLHTest.cpp
- test/unit/CompositeEDTest.cpp
- test/unit/CutTest.cpp
- test/unit/DataSetGeneratorTest.cpp
- test/unit/DistToolsTest.cpp
- test/unit/EDManagerTest.cpp
- test/unit/EventScaleTest.cpp
- test/unit/EventShiftTest.cpp
- test/unit/EventSystematicManagerTest.cpp
- test/unit/HistToolsTest.cpp
- test/unit/ObservableSetTest.cpp
Some of the core structure has been changed on the HMC branch, but the unit tests have not been updated. This PR deals with that. A lot of the changes come from that fact that the `ObsSet` is now created by observable names (strings) rather than indices (size_t), but other changes too.
Second small commit regards a bug in DataSetGenerator in the case when the number of requested events = number of events available, which should still be a valid request. (`max` is one less than `origData -> GetNEntries()`)
Note: There will be still be at least one unit test failing, until the bug fix for EventShift in PR #9 is not merged. After that they should all be fine.
> Fixed unit tests for HMC branch

- config/SConscript
Unless a more up-to-date compiler is used, by default the g++ compiler installed on CentOS7 uses the C++98 standard. This PR adds the `-std=c++11` compiler flag to enforce the C++11 standard. In so doing, our code can now use the multitude of ["new" features added in this standard!](https://en.cppreference.com/w/cpp/11) (I'm most excited for the ability to use range-based for-loops.)
In addition to this, I added the `-pedantic -Wall -Wextra -fdiagnostics-color` flags so that any warnings now get displayed when compiling, and they get nicely coloured.
I have tested the compilation under "standard" conditions used by Oxford SNO+ members: CentOS7 with the default g++ version 4.8.5, and default CentOS7 "snocave" dependencies. This master branch still compiles successfully, as do the …
> Set C++11 standard & Add compiler warning flags

- config/SConscript
This is identical to PR #14, except the change is made to the `hmc` branch.
This allows the benefits that these new compiler flags bring to be used by those working on the `hmc` branch, before the eventual merging of this branch into `master`.
As with PR #14, I confirmed that the addition of these flags have no effect on whether the code as-is compiles; compilation now just spews the numerous warnings present in the code base.
> Set C++11 standard & Add compiler warning flags -- For HMC

- src/teststat/BinnedNLLH.cpp
- src/teststat/BinnedNLLH.h
- src/teststat/QuadraticConstraint.h
- test/unit/BinnedNLLHTest.cpp
Currently, only symmetric constraints are possible for the `BinnedNLLH` class. This is an issue, given that some constraints we need to enforce in analyses (such as the solar flux constraint) are asymmetric.
This simple PR adds functionality to the `QuadraticConstraint` class so that either symmetric _or_ asymmetric constraints can be used, with a new associated constructor overload. If you want symmetric errors, just provide the mean and width, and for asymmetric errors provide the mean and two widths.
The `QuadraticConstraint` class is used mainly by the `BinnedNLLH` class; a similar function overload has been added there for the `SetConstraint()` method.
This modification has been designed so that existing code should function identically to how it did before with no changes needed.
I …
> Add asymmetric constraint

- src/core/DenseMatrix.h
- src/core/SparseMatrix.cpp
- src/core/SparseMatrix.h
- src/systematic/Convolution.cpp
It had been a while since I'd done anything with OXO before this week, but when I tried to compile I needed to make a couple of changes in the SparseMatrix class and the Convolution systematic that calls it, otherwise I got Armadillo errors at compilation.
I don't know if this is because our Armadillo install at Oxford has been updated? Or maybe it's something specific to my setup. But thought I'd see if anyone else had seen anything similar before digging into it too much? And a pull request was a simple way to show exactly what I needed to change.
So this shouldn't be merged (unless we understand it and it's not specific to my install/setup), but just wanted to open a discussion
> Changing some types to compile with armadillo

- src/fitutil/BinnedEDShrinker.cpp
- src/fitutil/BinnedEDShrinker.h
- src/optimise/MCMCSamples.cpp
- src/teststat/BinnedNLLH.cpp
- test/unit/BinnedEDShrinkerTest.cpp
This PR is designed to speed up the calculation of the LLH when using systematics. The BinnedEdShrinker is used to take out the buffer region and reassign bin numbers. Previously, the reassigning of bin numbers happened everytime the LLH was evaluated. This PR introduces a SetBinMap function which is only called the first time the shrinker is called. It then saves the corresponding bin numbers in a vector (fBinVec) to avoid having to do the nested loop of old and new bins (unshrunk and shrunk) every time.
Most of it is just moving code from BinnedEDShrinker::ShrinkDist to SetBinMap, so it looks like more has changed than it has really.
Bar any coding typos, I think the logic works unless there's some situation where the buffer would change during a fit, but maybe there's something I've …
> Feature syst speed

- src/systematic/Shift.cpp
- src/systematic/Shift.h
- test/unit/ScaleSystTest.cpp
- test/unit/ShiftSystTest.cpp
This adds a 'Shift' type of systematic, whereby a bin-by-bin shift can be applied in a given variable. This essentially used Scale as a template and did an add instead of a multiply. 
I've been using it for a bit and haven't seen any issues, but there's a bit of fiddly logic when determining what fraction of a bin's contents will be shifted into which bin, so fresh eyes on that in particular will be handy!
> add shift class of systematic

- src/dist/DistTools.cpp
- src/dist/DistTools.h
- test/unit/DistToolsTest.cpp
Sometimes you want to handle 3D histograms in your analysis! This PR adds functionality for that within `DistTools`, namely relevant methods for `ToHist()` and `ToTH3D()`.
A basic unit test is also added to `DistToolsTest.cpp`.
> Add TH3D capability to DistTools

- src/teststat/BinnedNLLH.cpp
- test/unit/BinnedNLLHTest.cpp
In creating the additional `QuadraticConstraint` overload to handle asymmetric errors, I foolishly put them in the wrong way round within the related  BinnedNLLH::SetConstraint() method.
This is just a quick one-line fix to resolve this issue!
> fix bug in SetConstraint()

- src/teststat/BinnedNLLH.cpp
- src/teststat/BinnedNLLH.h
Sometimes during setting up an analysis with OXO, one needs to look at the low-level information being calculated during the evaluation of the Binned negative log-likelihood, `BinnedNLLH::Evaluate()`.
This PR simply adds a debug mode boolean, `fDebugMode`, to the `BinnedNLLH` class. This gets considered within the `Evaluate()` method, where many lines of information are printed to `std::cout` relating to how `nLogLH` is calculated.
By default, debug mode is off, so won't change the functionality of existing code.
There could be a tiny performance hit to code, given that `if (fDebugMode)` gets repeatedly checked. Hopefully this is fairly minimal, as it is merely checking the status of a boolean member.
> Add a Debug option to BinnedNLLH class

- bin/SConscript
- config/buildhelp.py
This PR allows OXO to be compiled with scons either using Python v2 or v3.
Fortunately, only a few minor changes had to be made to make it simultaneously compatible!
I was getting annoyed at having to switch from my usual Python v3 that use in analysis to Python v2, solely to re-compile OXO. This PR solves that problem. It also moves this repo in line with the standard used in RAT.
> Make scons Python3 compatible

- examples/beestonBarlowLHH.cpp
- src/teststat/BinnedNLLH.cpp
- src/teststat/BinnedNLLH.h
- test/unit/BinnedNLLHTest.cpp
The main modification here is incorporating the Barlow-Beeston method for handling the MC statistical uncertainty in the BinnedNLLH test statistic. The user can set a bool when constructing the teststat (defaults off i.e not using Beeston-Barlow) and then can supply a vector of ints, the number of MC events generated for each PDF. [In typing this, I realise this could be handled better by doing this within Add PDF, to at least have a check that number of PDFs == the number of rates supplied. And should also check rates have been supplied if the flag is true.].
In the loop over bins, the beta value is calculated from the uncertainties. This scales the bin probability, and we calculate an extra penalty term to contribute to the likelihood. There's more details on the actual method in the …
> Beeston-Barlow in binned LLH

- src/systematic/Shift.cpp
- src/systematic/Shift.h
Following in the footsteps of the efficiency gains made in PR #25 for the `Scale` systematic, the same approach has been applied to the `Shift` systematic.
In order to construct the shift systematic response matrix, we:
1. Cache the bin mapping between elements of the matrix in the full space to the shifting subspace once at the start;
2. Construct the shifting response matrix in the 1D shifting axis only;
3. Use the bin mapping to create the full response matrix.
I have also moved the contents of the calculation of the fractional bin contribution for a given element into its own private method, using the same code as in `Scale` - so the bug fix there is included here too.
> Refactor Shift for efficiency

- src/systematic/ScaleFunction.cpp
- src/systematic/ScaleFunction.h
- test/unit/ScaleFuncSystTest.cpp
Adding a scaled systematic, but instead of just a linear scale with no offset, the user can input any function to scale bin edges by.
All the bin contribution calculations are taken from the original Scale systematics. The adding of the function is done in the same way as the Shape systematic. If you were to use a function that just returned a*x, where a is a parameter of the function, and x is the observable, the systematic behaves in the same way as the original Scale.
Tomorrow I'll add a Birk's scaling like function to use this in anger with!
> Add a functional scale systematic

- src/data/IO.cpp
- src/data/IO.h
- src/dist/DistTools.cpp
At the moment, if you invoke SaveHistogram() with a root file argument, the histogram gets saved without a title/name. So you have to get a bit funky with how you then access that histogram. This PR adds an option to give it a name when saving, in the same way this is already done for SaveDataset().
As for SaveDataset, the name gets passed to SaveHistogramRoot but not SaveHistogramH5, and defaults to "oxsx_saved"
Default behaviour should be the same, so you don't have to add any arguments for calls to SaveHistogram in your code if you don't want to, but just note now those histograms will be named
> Name histograms before saving them in root

- examples/DataSetGeneration.cpp
- examples/VaryingCDF.cpp
- examples/beestonBarlowLHH.cpp
- examples/simpleFit.cpp
- examples/simpleSystematicFit.cpp
- examples/systematicFit.cpp
- src/data/DataSetGenerator.cpp
- src/fitutil/EDManager.cpp
- test/unit/EDManagerTest.cpp
This PR makes minor modifications to the example macros, so that they now actually run without segfaulting. These crashes came from two problems:
- Historically, the normalisation parameter associated with a PDF in e.g. `BinnedNLLH` was the PDF name plus `"_norm"`. This feature has been changed a while ago, so that the parameter name is now just the same as the PDF name.
- Historically, the line `ObsSet  obsSet(0);` was valid; it hasn't been for a while: you now need to do something like `ObsSet  obsSet("axis1");`.
These problems have now been fixed in the examples, so that no crashes occur any more.
In addition, it was spotted that the lesser-used `EDManager` class still appended the `"_norm"`; this is different than the rest of the code. I have now modified this class to behave like …
> Fix examples; remove _norm addition from EDManager

- test/unit/BinnedEDGeneratorTest.cpp
- test/unit/BinnedEDTest.cpp
- test/unit/BinnedNLLHTest.cpp
- test/unit/DataSetGeneratorTest.cpp
- test/unit/DistToolsTest.cpp
- test/unit/GaussianTest.cpp
- test/unit/HistogramGetMultiDSlice.cpp
- test/unit/VaryingCDFTest.cpp
With the upgrade to Catch2 v3, how Catch's `Catch::Approx()` method handled tolerances changed, leading to a bunch of previously-passing unit tests suddenly.
This PR fixes these, now using the new recommended syntax of:
```
REQUIRE_THAT(test_val, Catch::Matchers::WithinAbs(exp_val, tolerance));
```
I have used a tolerance of 0.0001 throughout; all unit tests now pass.
In addition, there were a few places during compilation of the unit tests where the upgrade to C++17 led to new warnings. Those warnings have now been dealt with.
As a result of this PR (on top of the work of the previous two PRs!), we can now compile this repo's unit tests in C++17, and have all unit tests pass.
> unit test fixes

- src/fitutil/SystematicManager.cpp
This is a minor thing, but currently if you have a systematic you want to apply too all groups, you have to add it to your BinnedNLLH without an argument for the groups. This means if you are looping over systematics, some with groups and some without, you have to do something like:
```
for (std::map<std::string, Systematic *>::iterator it = systMap.begin(); it != systMap.end(); ++it){
if (systGroup[it->first] != "")
lh.AddSystematic(it->second, systGroup[it->first]);
else
lh.AddSystematic(it->second);
}
```
This PR would mean you no longer need the if statement so you can do something like:
```
for (std::map<std::string, Systematic *>::iterator it = systMap.begin(); it != systMap.end(); ++it){
lh.AddSystematic(it->second, systGroup[it->first]);
```
which is slightly tidier. 
The downside …
> Allow user to specify empty string for systematics group

- src/constraint/ConstraintManager.cpp
- src/constraint/ConstraintManager.h
- src/constraint/QuadraticConstraint.h
- src/constraint/RatioConstraint.h
- test/unit/ConstraintsTest.cpp
In the antinu fit we leave the two geoneutrino fluxes free as they're poorly constrained by geological models, however, the models do have constraints on the relative contributions. So the other antinu analyses have a constraint on the ratio of the two fluxes. Initially I thought this could be handled equivalently with a correlated constraint, but I don't think that's possible if the individual normalisations are unconstrained.
So here I've added an extra constraint class to have a quadratic penalty on the ratio of two parameters. I don't think it matters whether or not the parameters have individual/correlated constraints as well
I've added it to the constraints unit test and it seems to be doing what it's supposed to
> Adding Ratio Constraints

- src/optimise/MetropolisSampler.cpp
- src/optimise/MetropolisSampler.h
With this PR, parameters can be fixed in the Metropolis Sampler, similarly to how they can be for the Minuit optimiser class. In theory, it might be nicer if this was done in the base Optimiser class, but it gets a bit more complicated (but not impossible!) with some using samplers and some not, especially for the Hamiltonian MCMC with the other classes it uses. So for now I think it's ok adding these in as and when we need them.
I haven't tested this fully yet (we should maybe add optimiser unit tests!), but opened this now so it can be looked at
> Allow Parameters to be Fixed in Metropolis Sampler

- src/teststat/BinnedNLLH.cpp
Oof here's a bug and a half. In our BinnedNLLH teststat we have a few overloaded AddPDF and AddPDFs methods. When using AddPDFs, if you pass the systematic groups as an argument, it currently doesn't use the corresponding AddPDF with the syst groups as an argument.
Looks like I introduced it [here](https://github.com/snoplus/oxsx/commit/fb8265f165536f533b98aab19e4e01508f23876f#diff-b3e1de82bffd1909a5cca5a9fb918980b47cd97546802a4b66382b63ca58297e) and it made it through the great merge of 2022!
> Correctly use Systematic Groups in BinnedNLLH::AddPDFs

- src/fitutil/SystematicManager.cpp
Fixes a bug I introduced in #51. We need to return out of SystematicManager::Add after using the alternative overloaded method, otherwise systematics get added to fGroups[""] twice and it rightfully complains
Ok this, #60, and #58 can all be reviewed and merged. When they're in and we have a fix for #55, then the review/merge of #59 will be more straightforward
@dcookman sorry for all the noise! We could have a call if it's easier to discuss the ordering, or just wait til Wednesday's OXO call
> Avoid Adding Syst to Systman Groups Twice

- src/fitutil/SystematicManager.cpp
- test/unit/BinnedNLLHTest.cpp
This is the fix from #59, it also includes the tests from #62, but nothing else. So this and #62 can be reviewed and merged (if approved!)
(copying the text from #59):
So the big problem this fixes is for applying both at least one systematic in the global group, and at least one systematic in at least one other group. Firstly, previously, systematics were always applied to the OrignalEDs_, so when applying more than group to a PDF we'd do:
WorkingEDs_[j].SetBinContents(GetTotalResponse(groupName).operator()(OrignalEDs_.at(j).GetBinContents()));
then loop to the next groupName, and again do:
WorkingEDs_[j].SetBinContents(GetTotalResponse(groupName).operator()(OrignalEDs_.at(j).GetBinContents()));
So the last group is the only one that would be applied!
Also there was some funky logic with …
> Fix for systematics in different groups

- src/fitutil/BinnedEDManager.h
- src/teststat/BinnedNLLH.h
Doing "proper" analyses in OXO doesn't make much sense with the DIRECT method, unless you're not including systematics or shrinking. As a result, I've set the default `NormFittingStatus` for `BinnedED` objects to now be `INDIRECT`, which has the correct general behaviour when shrinking and systematics are applied. If you still want to use the (marginally faster) `DIRECT` mode, go ahead, but now at least you can't use the wrong mode accidentally.
> Set default NormFittingStatus to INDIRECT

- .gitignore
- CMakeLists.txt
- README.md
- examples/CMakeLists.txt
- examples/data/CMakeLists.txt
- examples/pdf/CMakeLists.txt
- examples/plot/CMakeLists.txt
- oxsx_container.def
- src/CMakeLists.txt
- src/config/CMakeLists.txt
- src/constraint/CMakeLists.txt
- src/core/CMakeLists.txt
- src/core/DenseMatrix.h
- src/core/SparseMatrix.h
- src/count/CMakeLists.txt
- src/cut/CMakeLists.txt
- src/data/CMakeLists.txt
- src/dist/CMakeLists.txt
- src/eventSystematic/CMakeLists.txt
- src/fitutil/CMakeLists.txt
- src/function/CMakeLists.txt
- src/histogram/CMakeLists.txt
- src/interval/CMakeLists.txt
- src/optimise/CMakeLists.txt
- src/plot/CMakeLists.txt
- src/rand/CMakeLists.txt
- src/systematic/CMakeLists.txt
- src/teststat/CMakeLists.txt
- test/CMakeLists.txt
- test/unit/CMakeLists.txt
This PR does two main things:
1. Create a file `oxsx_container.def`, which can be used to create a Container which holds all of the external dependencies necessary to run OXSX.
2. Add a bunch of CMake files, so that one can compile OXSX within the container.
Some instructions about how to run this has been added to the README.
I also removed a couple of redundant includes in some files, as a cleanup.
> DEF file for Container, and CMake build code
